### PR TITLE
Convert existing newsletters to markdown

### LINKED ISSUE #40: Add newsletters page
The [newsletters](https://ivoa.net/newsletter/index.html) will have to be added in the `static/newsletter/` directory.

The newsletter of March already in this repo is incomplete.

### PR DESCRIPTION
**Pull request by gmantele**
Here are the first transcribed newsletters. More will come in the next days.

Fixes #40

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
@gmantele Would you mind splitting up this PR and putting the stylesheet and short code updates in another PR?

This should be straightforward by doing a rebase, editing the commit, and then performing a soft reset. Then you can make separate commits. I would say if you do this just leave anything specific to newsletter style in there, too, but it would be nice to evaluate only the newsletters themselves.

I would find this extremely useful to be able to merge that first so I can use it for some pages I'm working on. (Just not sure of the timescale for merging this PR since you said there are more newsletters that need to be ported.)

**Comment by gmantele** [comment]
This PullRequest is based on the branch `iss40-add-newsletters` which is derived from the branch `iss84-add-shortcodes-for-image-placement`. This origin branch is needed for the shortcodes that are defined there and are required for this PullRequest. Once `iss84...` will be merged, I will apply again a force rebase for this branch, but this time based on the `main` branch. This way, it should give a cleaner history.

**Review by molinaro-m — APPROVED** [review]
I'm fine with approach and result.
The PR for iss84 is approved to, so rebase and merge can follow with these two.

**Comment by JeremyMcCormick** [comment]
I merged the PR with the short codes. 

Please update the branch for this PR accordingly as it commits some similar utilities.

**Pull request merged**
