### PR TITLE
Convert about and contacts pages

### LINKED ISSUE #60: Add contacts page
Add [contacts page](https://ivoa.net/about/contacts.html) to `content/about/contacts.md`.

### PR DESCRIPTION
**Pull request by molinaro-m**
should fix #60 and #2 (partly)

### CODE REVIEW

**Comment by molinaro-m** [comment]
Added the contacts page
I'll work out the members-contact now (even if it is linked to this explicitly)

**Comment by molinaro-m** [comment]
Hi @JeremyMcCormick , @gmantele 
This is now rebased on the shortcodes additions (even if not using them).
Please, check whether it's OK to merge it.

**Comment by JeremyMcCormick** [comment]
> Hi @JeremyMcCormick , @gmantele This is now rebased on the shortcodes additions (even if not using them). Please, check whether it's OK to merge it.

It seems like the short code changes were not rebased out. I still see them in the commit log.

You might need to `git fetch origin` first?

**Comment by molinaro-m** [comment]
I think I get what's the issue here (my fault).
There's the branch on origin that diverged from my local due to rebasing and merging.
I wonder if there's a solution or if its better I drop this PR, delete and redo the branches, and then restart the merge request from a clean situation.

**Comment by JeremyMcCormick** [comment]
> I think I get what's the issue here (my fault).
> 
> There's the branch on origin that diverged from my local due to rebasing and merging.
> 
> I wonder if there's a solution or if its better I drop this PR, delete and redo the branches, and then restart the merge request from a clean situation.

I mentioned this on the other PR - just drop the shortcode commits entirely using a rebase. Should work fine I think...

**Review by JeremyMcCormick — APPROVED** [review]
This looks fine in preview.

There are additional commits showing up that are already on `main` but it shouldn't be a problem. Doing `git diff main` on this branch shows only the page update. No conflicts should occur when merging.

**Pull request merged**
