### PR TITLE
Initial porting of existing pages

### PR DESCRIPTION
**Pull request by KlaasYK**
Existing pages can be put under the `content/pages/<category>` directory. 
Linking on the main page is done in the `content/_index.html` using a `{{<ref "pages/about/what_is_vo">}}` instead of a real URI.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
Is the `date:` field in the markdown files filled in manually?

If so, is this something that can and should be automated so it doesn't need to be done by hand every time someone modifies a page? (I don't know if it is easily possible but it would be nice.)

**Review by molinaro-m — COMMENTED** [review]
For the "gettng started" page, I'd prefer seeing a _one use case" limited translation rather then a lorem ipsum, just to see images and external links in action.
Otherwise I'm fine, also because we are testing and building.

I leave to @JeremyMcCormick the formal approval, based on his question about the issue purpose.

**Comment by KlaasYK** [comment]
@JeremyMcCormick the date is not updated automatically. I think there are options for that in Hugo based on the git date: https://gohugo.io/methods/page/gitinfo/

@molinaro-m I will see if I can replace the iorem ipsum with something more "real" and also include links/images :)

**Review by JeremyMcCormick — APPROVED** [review]
Good example of porting a page. I will approve so it can be put into the test site.

**Pull request merged**
