### PR TITLE
Add getting started page

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
I have ported the "Getting Started" page to markdown and added required graphical assets. I did not exactly replicate the image placement from [this page](https://ivoa.net/astronomers/getting_started.html), but I think this is fine for now.

~~I also enabled embedding of HTML in markdown pages for the site.~~

### CODE REVIEW

**Comment by gmantele** [comment]
It is possible to get a nice zoom in effect with Hugo. I did it for all figures on the CDS website (ex: look at the 'Figure 1' on this page: <https://cds.unistra.fr/blog/2024/02/20-a-new-look-for-the-cds-website/>).

**Comment by molinaro-m** [comment]
I think that the porting from this PR is enough for now, or maybe even too much.
I suppose that, once we have the .md website ready, we can rethink the structure of that page (maybe templating it together with similat ones).
I wouldn't spend more effort on this than what's already done.

**Review by molinaro-m — APPROVED** [review]
page translation is fine for me

**Comment by JeremyMcCormick** [comment]
> just for my understanding: why wasn't this merged?

I need to do a little work on this for image placement and taking out some config I changed that allows raw HTML, which @gmantele suggested we should not enable, and I agree. I'm going to mark this as draft for now so it doesn't get merged before these fixes are made.

**Comment by JeremyMcCormick** [comment]
This looks a bit different from the old website but seems fine to me:

image

**Pull request merged**
