### PR TITLE
Iss101 mobile responsiveness

### PR DESCRIPTION
**Pull request by szautkin**
Screenshot 2024-12-13 at 3 33 25 PM
Screenshot 2024-12-13 at 3 33 14 PM
Screenshot 2024-12-13 at 3 33 06 PM

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
This needs to be on a branch within the main repo for CI and not a personal fork.

Please close this and reopen with the same branch name on the primary repo.

Thanks!

**Review by JeremyMcCormick — CHANGES_REQUESTED** [review]
This looks amazing, but please close this PR and open a new one on a branch with the same name off the primary repository rather than a fork. 

The CI to deploy the test site will not run successfully from a fork, and we need it for this PR in order to check and the updates on a mobile browser.

**Comment by gmantele** [comment]
Just a brief comment: the command `make preview` do not work anymore. PostCSS must be installed on the local machine in order to compile the TailWind CSS.

**Comment by JeremyMcCormick** [comment]
Moved to #107

**Pull request closed without merging**
