### PR TITLE
Add search capability

### LINKED ISSUE #88: Add a Search Page feature
Add the capability to search pages using some keywords and eventually some filters.

### PR DESCRIPTION
**Pull request by gmantele**
This PR aims to add an indexing capability using [PageFile](https://pagefind.app/) and then to add somewhere in the IVOA pages the search form and results.

Fixes #88

### CODE REVIEW

**Comment by gmantele** [comment]
Currently, PageFind is all configured. The Makefile has been adapted to index pages after their generation (PageFind indexes HTML files). This works well with the `preview` and the new `html` targets.

Left to do:

- [ ] Adapt the CI to generate the search index (either using the Makefile or using directly the commands)
- [ ] Add the search field
- [ ] Add the search results

Questions to answer:

- where should be the search field?
  - in the top navigation bar?
  - visible by default or a button should be clicked to show a search form (including the search field and eventually some filters)?
- where should be displayed the search results?
  - in a contextual menu after having entered some letters?
  - in a dialog?
  - in a separate page?
- do we want to filter the search results?
  - by date?
  - by section/direction? (e.g. newsletter, members, ...)
  - by tag? (then we should put some in our content pages)

Two examples of search capabilities with PageFind:
- the [CDS Website](https://cds.unistra.fr/) (using Hugo+PageFind)
- the [PageFind website](https://pagefind.app/)

**Comment by gmantele** [comment]
For the moment, the current prototype uses the CSS and JS of the same feature on the CDS website. They have been slightly adapted, but they should be completely adapted to the desired features and style of the IVOA website.

Anyway, the search capability is fully working here. You can already test it if you want, although it may be even more interesting while we will have the newsletters (which contain a lot of content).

Currently, the search capability is only available on a single dedicated page (`/search/` ; a link is visible, temporarily at first position, in the top navigation bar). We have to decide where how we would like to trigger this search capability. A dedicated page like now or a modal dialog available on all pages when clicking on search button/icon?

**Comment by gmantele** [comment]
I have not yet adapted the CI, so you will have to test this feature on your local repository ; it does not work yet on `https://webtest.ivoa.info/v/iss88-search-index//search/` as PageFind is not installed and run.

To do that locally on your machine, you will have to:

1. Checkout this branch
2. Run `make preview` ; this will install PageFind, generate the search index and open the generated website in your web browser.

Only running the Hugo command is no more enough if you want to use the search capability.

**Comment by JeremyMcCormick** [comment]
This looks great!

Is this ready to be merged? Or do you have more changes planned?

**Comment by gmantele** [comment]
As I said, it is not yet ready to be merged. I still have few style things to do, and tuning of the search engine.

And, we also have to decide
- if this search feature is nice this way?
- Do we want it as a dialog available on any page of the website (as on the CDS website)?
- Is the link on the top left in the main nav bar is OK or should it be somewhere else?

**Comment by molinaro-m** [comment]
I checked out and tried the solution on my laptop and it worked seamlessly (even before I realised it had finished).
We have to remember to discuss Grégory's questions in the comment above at our next vconf/meeting.

My preference: nice to have, dialog-wise, as a "lens" at the right end of the nav-bar.

**Comment by JeremyMcCormick** [comment]
> As I said, it is not yet ready to be merged. 

My apologies, I see this is marked as draft.

**Comment by JeremyMcCormick** [comment]
> Questions to answer:

I have no problem to defer most of these questions until a later update in order to just get the search functionality enabled and working on the site first. From my perspective, you can do whatever you think is best for the initial implementation and then we can go from there. We'll need to get feedback about it from a wider audience anyways than just our small development group. :)

**Comment by gmantele** [comment]
Here is a first version of the search module in the IVOA website. It has room for improvement in future PullRequests in function of desired additional features:

- search module as a popup
- add a filter on the category of pages (e.g. newsletter or other)
- change sort type and order (currently from the most recent to the oldest)
- add a filter on eventual tags that could be added in the future (this feature is already in the code but just disabled)
- ...

The CI has been updated in order to install PageFind (if not already installed or in the cache of GitHub) and to generate the index with PageFind. The preview version is now fully operational ; you can search on the [search page](https://webtest.ivoa.info/v/iss88-search-index//search/).

**Comment by gmantele** [comment]
I have also done two other unrelated things in this PullRequest:

- upgrade Hugo (up to 0.135.0 ; not the latest, but a quite recent one ; further upgrade will be frequently done)
- optimize all newsletters images in order to decrease the volume of data to deploy (from 137MB to 42MB), and then to speed up the deployment (from ~6min to 3min).

Now, I consider this PullRequest as ready for review and merge.

**Review by molinaro-m — APPROVED** [review]
Updated my branch locally and tested with the make preview.
Looks perfect to me.
Approved.

**Comment by JeremyMcCormick** [comment]
Absolutely fantastic @gmantele! :)

I tested as well using `make preview` and confirmed that the search is working, so I will merge.

**Pull request merged**
