### PR TITLE
Convert member organizations and contact member pages

### LINKED ISSUE #58: Add member organizations page
Add [member organizations](https://ivoa.net/about/member-organizations.html) under `about/member-organizations`.

### PR DESCRIPTION
**Pull request by molinaro-m**
this should fix #58 , could require further refinement, uses #85 for left-side images w.r.t. the text

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
I merged the PR that added the shortcodea separately. Can you review your changes here to make sure they do not conflict? I think maybe you can use the ones that Gregory added.

**Comment by molinaro-m** [comment]
the other PR I have in place was started from a "pre-shortcode" version of main. This one was built on top of Gregory's work, it shouldn't conflict with current main.
I think we can wait for PR #86 to be merged, as a check, and then move also this one in.

**Comment by JeremyMcCormick** [comment]
> the other PR I have in place was started from a "pre-shortcode" version of main. This one was built on top of Gregory's work, it shouldn't conflict with current main. I think we can wait for PR #86 to be merged, as a check, and then move also this one in.

Can you rebase out the changes that duplicate what is on `main`?

I believe `git fetch origin && git rebase -i main` should work. Then they should disappear.

**Comment by molinaro-m** [comment]
not sure what happened
I suppose my git skills are lacking
but the recipe you suggested bring in no changes, a push simply states nothing to do

**Comment by JeremyMcCormick** [comment]
> not sure what happened
> 
> I suppose my git skills are lacking
> 
> but the recipe you suggested bring in no changes, a push simply states nothing to do
> 

You can just mark the first two commits that add the shortcodes as "d" (drop) in the rebase to remove them entirely - then force push (`git push -f`). That should clean it up. Then recheck your local Hugo site to make sure it looks okay.

**Review by JeremyMcCormick — APPROVED** [review]
Page content looks fine.

However, I just noticed that `about/member-contacts` is not linked from the navigation menus, only from `about/what_is_ivoa`.

I'll approve this PR, but you may want to add a link to the navigation menu for that page so it is more easily accessible.

**Pull request merged**
